likes/urls.py
from django.urls import path
from .views import post_view, like_post

app_name = 'likes'

urlpatterns = [
  path('', post_view, name='post-list'),
  path('likes/', like_post, name='like-post'),
]

mysite/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
import views

urlpatterns = [
    path('admin/', admin.site.urls),
      
] + i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path('', views.index),
    path('aboutUs.html', views.aboutUs),
    path('gallery.html', views.gallery),
    path('index.html', views.index),
    path('login.html', views.login),
    path('likes/', include('likes.urls', namespace='likes')),
    path('likes/aboutUs.html', views.aboutUs),
    path('likes/gallery.html', views.gallery),
    path('likes/index.html', views.index),
    path('likes/login.html', views.login) 
)

likes/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
  title = models.CharField(max_length = 150)
  body = models.TextField()
  liked = models.ManyToManyField(User, default=None, blank=True, related_name='liked')
  updated = models.DateTimeField(auto_now=True)
  created = models.DateTimeField(auto_now_add=True)
  author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author')

  def __str__(self):
    return str(self.title)

  @property
  def num_likes(self):
    return self.liked.all().count()


LIKE_CHOICES = (
  ('Like', 'Like'),
  ('Unlike', 'Unlike'),
)

class Like(models.Model):
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  post = models.ForeignKey(Post, on_delete=models.CASCADE)
  value = models.CharField(choices=LIKE_CHOICES, default = 'Like', max_length = 10)

  def __str__(self):
    return str(self.post)

likes/views.py
from django.shortcuts import render, redirect
from .models import Post, Like

# Create your views here.
def post_view(request):
  qs = Post.objects.all()
  user = request.user

  context = {
    'qs' : qs,
    'user' : user,
  }

  return render(request, 'likes/likes.html', context)


def like_post(request):
  user = request.user
  if request.method == 'POST':
    post_id = request.POST.get('post_id')
    post_obj = Post.objects.get(id=post_id)

    if user in post_obj.liked.all():
      post_obj.liked.remove(user)
    else:
      post_obj.liked.add(user)

    like, created = Like.objects.get_or_create(user=user, post_id=post_id)

    if not created:
      if like.value == 'Like':
        like.value = 'Unlike'
      else:
        like.value = 'Like'

    like.save()
  return redirect('likes:post-list')

views.py
from django.shortcuts import render

def index(request):
  return render(request, "index.html")

def login(request):
  return render(request, "login.html")

def gallery(request):
  return render(request, "gallery.html")

def aboutUs(request):
  return render(request, "aboutUs.html")

templates/aboutUs.html
<!doctype html>
<html lang="ru" prefix="og: http://ogp.me/ns#">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="docsearch:language" content="ru">
<meta name="docsearch:version" content="5.0">
<title>Cyberpunk 2022</title>
<!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
<link rel="stylesheet" href="https://bootstrap5.ru/css/docs.css">
<!-- Favicons -->
<link rel="icon" type="image/png" href="Resources/favicon.png"/>

<style>
  .bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
  }

  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 3.5rem;
    }
  }
</style>
    <!-- Custom styles for this template -->
    {% load static %}
    <link href="{% static 'style.css' %}" rel="stylesheet"></head>
<body>
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Cyberpunk2022</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto mb-2 mb-md-0">
          <li class="nav-item active">
            <a class="nav-link" aria-current="page" href="index.html">Главная</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="gallery.html">Галерея</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="aboutUs.html">О нас</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="login.html">Авторизация</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

<main>

  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" preserveaspectratio="xMidYMid slice" role="img" focusable="false">
          <rect width="100%" height="100%" fill="#777">
          <img src="{% static 'Resources/big_1.jpg' %}">
          </rect></svg>

        <div class="container">
          <div class="carousel-caption">
            <h1>СОЗДАЙТЕ СВОЙ МИР КИБЕРПАНКА</h1>
            <p>Уничтожайте всех, кто встанет у вас на пути, будь то корпоративная охрана и полиция, банды и другие наёмники, улучшайте свою репутацию и получайте более выгодные заказы.</p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" preserveaspectratio="xMidYMid slice" role="img" focusable="false">
          <rect width="100%" height="100%" fill="#777">
            <img src="{% static 'Resources/big_2.jpg' %}">
          </rect></svg>

        <div class="container">
          <div class="carousel-caption">
            <h1>ПОСЕЛИТЕСЬ В ГОРОДЕ БУДУЩЕГО</h1>
            <p>Живите в ритме фантастического города: выбирайтесь в заброшенные районы, где бесчинствуют банды, закупайтесь в многолюдном центре города и одалживайте у корпораций новейшее снаряжение на частной территории.</p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" preserveaspectratio="xMidYMid slice" role="img" focusable="false"><rect width="100%" height="100%" fill="#777">
          <img src="{% static 'Resources/big_3.jpg' %}">
        </rect></svg>

        <div class="container">
          <div class="carousel-caption">
            <h1>СТАНЬТЕ ЛЕГЕНДОЙ</h1>
            <p>Проворачивайте смелые аферы и заводите дружбу с харизматичными персонажами, на жизнь которых влияют ваши решения.</p>
          </div>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>


  <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->

  <div class="p-5 mb-4 bg-little-yellow rounded-3">
      <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold little-dark">CD Project Blue</h1>
        <p class="col-md-8 fs-4 little-dark">Мы международная команда энтузиастов-экспертов, стремящихся создать незабываемые игровые впечатления. В CPB всем предлагается объединить свой талант и воображение с передовыми технологиями для разработки развлечений невероятного уровня.</p>
      </div>
    </div>

    <div class="row align-items-md-stretch">
      <div class="col-md-6">
        <div class="h-100 p-5 text-white bg-dark rounded-3">
          <h2>Студенты & Начинающие специалисты</h2>
          <p>Присоединяйтесь к нам и начните свой профессиональный путь в компании, которая процветает благодаря воображению и инновациям, чтобы создавать развлечения невероятного уровня.</p>
        </div>
      </div>
      <div class="col-md-6">
        <div class="h-100 p-5 bg-little-yellow border rounded-3">
          <h2 class = "little-dark">Доступность</h2>
          <p class = "little-dark">Мы распространяем наши игры совершенно бесплатно, чтобы даже дети в Африке могли насладиться нашими продуктами.</p>
        </div>
      </div>
    </div>

  <!-- FOOTER -->
  <footer class="container">
    <p class="float-right"><a href="#">Наверх</a></p>
    <p>&copy; 2021-2022 Team11, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
  </footer>
</main><script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.bundle.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/base.html
<!doctype html>
<html lang="ru" prefix="og: http://ogp.me/ns#">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="docsearch:language" content="ru">
<meta name="docsearch:version" content="5.0">
<title>Cyberpunk 2022 | {% block title %}{% endblock title %}</title>
<!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
<link rel="stylesheet" href="https://bootstrap5.ru/css/docs.css">
<!-- Favicons -->
<link rel="icon" type="image/png" href="Resources/favicon.png"/>

  <!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>

<style>
  .bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
  }

  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 3.5rem;
    }
  }
</style>
    <!-- Custom styles for this template -->
    {% load static %}
    <link href="{% static 'style.css' %}" rel="stylesheet"></head>
<body>
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Cyberpunk2022</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto mb-2 mb-md-0">
          <li class="nav-item active">
            <a class="nav-link" aria-current="page" href="index.html">Главная</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="gallery.html">Галерея</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="aboutUs.html">О нас</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="login.html">Авторизация</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

<main>

  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" preserveaspectratio="xMidYMid slice" role="img" focusable="false">
          <rect width="100%" height="100%" fill="#777">
          <img src="{% static 'Resources/big_1.jpg' %}">
          </rect></svg>

        <div class="container">
          <div class="carousel-caption">
            <h1>СОЗДАЙТЕ СВОЙ МИР КИБЕРПАНКА</h1>
            <p>Уничтожайте всех, кто встанет у вас на пути, будь то корпоративная охрана и полиция, банды и другие наёмники, улучшайте свою репутацию и получайте более выгодные заказы.</p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" preserveaspectratio="xMidYMid slice" role="img" focusable="false">
          <rect width="100%" height="100%" fill="#777">
            <img src="{% static 'Resources/big_2.jpg' %}">
          </rect></svg>

        <div class="container">
          <div class="carousel-caption">
            <h1>ПОСЕЛИТЕСЬ В ГОРОДЕ БУДУЩЕГО</h1>
            <p>Живите в ритме фантастического города: выбирайтесь в заброшенные районы, где бесчинствуют банды, закупайтесь в многолюдном центре города и одалживайте у корпораций новейшее снаряжение на частной территории.</p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" preserveaspectratio="xMidYMid slice" role="img" focusable="false"><rect width="100%" height="100%" fill="#777">
          <img src="{% static 'Resources/big_3.jpg' %}">
        </rect></svg>

        <div class="container">
          <div class="carousel-caption">
            <h1>СТАНЬТЕ ЛЕГЕНДОЙ</h1>
            <p>Проворачивайте смелые аферы и заводите дружбу с харизматичными персонажами, на жизнь которых влияют ваши решения.</p>
          </div>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>


  <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->

  <div class='ui container'>
    {% block content %}
    {% endblock content %}
  </div>

  {% block scripts %}
  {% endblock scripts %}

  <!-- FOOTER -->
  <footer class="container">
    <p class="float-right"><a href="#">Наверх</a></p>
    <p>&copy; 2021-2022 Team11, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
  </footer>
</main><script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.bundle.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/gallery.html
<!doctype html>
<html lang="ru" prefix="og: http://ogp.me/ns#">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="docsearch:language" content="ru">
<meta name="docsearch:version" content="5.0">
<title>Cyberpunk 2022 | {% block title %}{% endblock title %}</title>
<!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
<link rel="stylesheet" href="https://bootstrap5.ru/css/docs.css">
<!-- Favicons -->
<link rel="icon" type="image/png" href="Resources/favicon.png"/>

  <!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>

<style>
  .bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
  }

  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 3.5rem;
    }
  }
</style>
    <!-- Custom styles for this template -->
    {% load static %}
    <link href="{% static 'style.css' %}" rel="stylesheet"></head>
<body>
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Cyberpunk2022</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto mb-2 mb-md-0">
          <li class="nav-item active">
            <a class="nav-link" aria-current="page" href="index.html">Главная</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="gallery.html">Галерея</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="aboutUs.html">О нас</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="login.html">Авторизация</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

<main>

  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" preserveaspectratio="xMidYMid slice" role="img" focusable="false">
          <rect width="100%" height="100%" fill="#777">
          <img src="{% static 'Resources/big_1.jpg' %}">
          </rect></svg>

        <div class="container">
          <div class="carousel-caption">
            <h1>СОЗДАЙТЕ СВОЙ МИР КИБЕРПАНКА</h1>
            <p>Уничтожайте всех, кто встанет у вас на пути, будь то корпоративная охрана и полиция, банды и другие наёмники, улучшайте свою репутацию и получайте более выгодные заказы.</p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" preserveaspectratio="xMidYMid slice" role="img" focusable="false">
          <rect width="100%" height="100%" fill="#777">
            <img src="{% static 'Resources/big_2.jpg' %}">
          </rect></svg>

        <div class="container">
          <div class="carousel-caption">
            <h1>ПОСЕЛИТЕСЬ В ГОРОДЕ БУДУЩЕГО</h1>
            <p>Живите в ритме фантастического города: выбирайтесь в заброшенные районы, где бесчинствуют банды, закупайтесь в многолюдном центре города и одалживайте у корпораций новейшее снаряжение на частной территории.</p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" preserveaspectratio="xMidYMid slice" role="img" focusable="false"><rect width="100%" height="100%" fill="#777">
          <img src="{% static 'Resources/big_3.jpg' %}">
        </rect></svg>

        <div class="container">
          <div class="carousel-caption">
            <h1>СТАНЬТЕ ЛЕГЕНДОЙ</h1>
            <p>Проворачивайте смелые аферы и заводите дружбу с харизматичными персонажами, на жизнь которых влияют ваши решения.</p>
          </div>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>


  <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->

  <div class="album py-5 bg-dark">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
            <img src = "{% static 'Resources/gameplay_1.jpg' %}">
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
            <img src = "{% static 'Resources/gameplay_2.jpg' %}">

          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
            <img src = "{% static 'Resources/gameplay_3.jpg' %}">

          </div>
        </div>

        <div class="col">
          <div class="card shadow-sm">
            <img src = "{% static 'Resources/gameplay_4.jpg' %}">

          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
            <img src = "{% static 'Resources/gameplay_5.jpeg' %}">
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
            <img src = "{% static 'Resources/gameplay_6.jpg' %}">

          </div>
        </div>

        <div class="col">
          <div class="card shadow-sm">
            <img src = "{% static 'Resources/gameplay_7.jpg' %}">

          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
            <img src = "{% static 'Resources/gameplay_8.jpg' %}">

          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
            <img src = "{% static 'Resources/gameplay_9.jpg' %}">

          </div>
        </div>
      </div>
    </div>
  </div>


  <div class='ui container'>
    {% block content %}
    {% endblock content %}
  </div>

  {% block scripts %}
  {% endblock scripts %}

  <!-- FOOTER -->
  <footer class="container">
    <p class="float-right"><a href="#">Наверх</a></p>
    <p>&copy; 2021-2022 Team11, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
  </footer>
</main><script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.bundle.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/likes/likes.html
{% extends 'base.html' %}

{% block title %}
{% endblock title %}

{% block content %}
  {% for obj in qs %}
     <h1>{{ obj.title }}</h1>
     <p>{{ obj.body }}</p>
     <form action="{% url 'likes:like-post' %}" method='POST' class='like-form' id='{{ obj.id }}'>
       {% csrf_token %}
       <input type='hidden' name='post_id' value="{{ obj.id }}">
       <button type="submit" class="ui button like-btn{{obj.id}}">
            {% if user not in obj.liked.all %}
                Like
            {% else %}
                Unlike
            {% endif %}
        </button>
        <div class="ui grid">
            <div class="column">
                <div class="like-count{{obj.id}}"> {{obj.num_likes}} </div>
            </div>
            <div class="column">
                likes
            </div>
        </div>
     </form>
  {% endfor %}
{% endblock content %}

{% block scripts %} 
    <script>
        $( document ).ready(function() {

            $('.like-form').submit(function(e){
                e.preventDefault()
                
                const post_id = $(this).attr('id')
                
                const likeText = $(`.like-btn${post_id}`).text()
                const trim = $.trim(likeText)

                const url = $(this).attr('action')
                
                let res;
                const likes = $(`.like-count${post_id}`).text()
                const trimCount = parseInt(likes)

                var data = [{"csrfmiddlewaretoken": $('input[name=csrfmiddlewaretoken]').val(),},
                            {"post_id" : post_id}];

                var token =  $('input[name=csrfmiddlewaretoken]').val()
                $.ajaxSetup({
                    beforeSend: function(xhr) {
                        xhr.setRequestHeader('csrfmiddlewaretoken', token);
                    }
                });
              
                $.ajax({
                    type: 'POST',
                    url: url,
                    dataType: 'json',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify({
                        data
                    }),
                    success: function(response) {
                        if(trim === 'Unlike') {
                            $(`.like-btn${post_id}`).text('Like')
                            res = trimCount - 1
                        } else {
                            $(`.like-btn${post_id}`).text('Unlike')
                            res = trimCount + 1
                        }

                        $(`.like-count${post_id}`).text(res)
                    },
                    error: function(response) {
                        console.log('error', response)
                    }
                })

            })
        });
    </script>
{% endblock scripts %}